### ISSUE TITLE
No dbQuoteIdentifier method?

### ISSUE THREAD

**Issue by cpsievert** [rstats-db/RSQLite#99] opened 2015-08-28 21:08 UTC
Here's an example where it's relevant

```r
library(dplyr)
db <- src_sqlite(tempfile(fileext = ".sqlite3"), create = TRUE)

schema <- "https://gist.githubusercontent.com/cpsievert/151e48f1f452017c8936/raw/a0b3a74d057ac2b9e935ba0b49999f621bd67651/mtcars.sqlite3"
curl::curl_download(schema, basename(schema))

s <- readChar(basename(schema), 
              file.info(basename(schema))$size, 
              useBytes = TRUE)

library(DBI)
dbSendQuery(db$con, s)
dbListFields(db$con, "mtcars")
#>  [1] "makeModel" "mpg"       "cyl"       "disp"      "hp"        "drat"      "wt"       
#>  [8] "qsec"      "vs"        "am"        "gear"      "carb"    
```

```r
db <- src_sqlite(tempfile(fileext = ".sqlite3"), create = TRUE)
dbSendQuery(db$con, dbQuoteIdentifier(db$con, s))
#> Error in sqliteSendQuery(conn, statement) : 
#>   error in statement: near ""CREATE TABLE mtcars(
#>     ""makeModel"" TEXT PRIMARY KEY,
#>     ""mpg"" REAL,
#>     ""cyl"" INTEGER,
#>     ""disp"" INTEGER,
#>     ""hp"" INTEGER,
#>     ""drat"" REAL,
#>     ""wt"" REAL,
#>     ""qsec"" REAL,
#>     ""vs"" INTEGER,
#>     ""am"" INTEGER,
#>     ""gear"" INTEGER,
#>     ""carb"" INTEGER
#>   );
#> "": syntax error
```

**Comment by krlmlr** [comment] 2015-10-27 20:06
Thanks. I can't reproduce this in the dev version. Could you please post devtools::session_info()?

**Comment by cpsievert** [comment] 2015-10-27 21:33
```r
> session_info()
Session info -------------------------------------------------------------------
 setting  value
 version  R version 3.2.2 (2015-08-14)
 system   x86_64, darwin13.4.0
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 tz       Australia/Melbourne
 date     2015-10-28

Packages -----------------------------------------------------------------------
 package    * version date       source
 assertthat   0.1     2013-12-06 CRAN (R 3.2.0)
 curl         0.9.3   2015-08-25 CRAN (R 3.2.0)
 DBI        * 0.3.1   2014-09-24 CRAN (R 3.2.0)
 devtools   * 1.9.1   2015-09-11 CRAN (R 3.2.0)
 digest       0.6.8   2014-12-31 CRAN (R 3.2.0)
 dplyr      * 0.4.3   2015-09-01 CRAN (R 3.2.0)
 fortunes     1.5-2   2013-12-14 CRAN (R 3.2.0)
 magrittr     1.5     2014-11-22 CRAN (R 3.2.0)
 memoise      0.2.1   2014-04-22 CRAN (R 3.2.0)
 R6           2.1.1   2015-08-19 CRAN (R 3.2.0)
 Rcpp         0.12.1  2015-09-10 CRAN (R 3.2.0)
 RSQLite      1.0.0   2014-10-25 CRAN (R 3.2.0)
```

**Comment by krlmlr** [comment] 2015-10-27 21:42
Thanks. Probably I misunderstood the problem here. I think `dbQuoteIdentifier()` is not needed here at all. Try `dbQuoteIdentifier(db$con, "identifier")` to see what it does. Why do you use `dbSendQuery(db$con, s)` in your first example, but `dbSendQuery(db$con, dbQuoteIdentifier(db$con, s))` in your second?

**Comment by krlmlr** [comment] 2015-11-10 21:37
Closing for now, please feel free to reopen.

**Closed by krlmlr** 2015-11-10 21:37 UTC
