### ISSUE TITLE
double column are converted to int mistakenly

### ISSUE THREAD

**Issue by mahl** [rstats-db/RSQLite#130] opened 2016-02-25 03:42 UTC
When fetching records from a table with columns of type double, the data in the column are converted to int mistakenly. This may have to do with the fact that some of the data in the column are actually int values.

For example:
1, 2, 3, 1.01 are converted to 1, 2, 3, 1.

**Comment by krlmlr** [comment] 2016-03-02 08:20
Thanks for reporting this issue. This may be related to the fact that the data type in a column is not fixed in SQLite. Would you like to contribute a pull request?

**Comment by hadley** [comment] 2016-03-16 19:54
I'd say this is a duplicate of #74

**Closed by hadley** 2016-03-16 19:54 UTC
