### ISSUE TITLE
"Closing result set with pending rows" warning and partial result

### ISSUE THREAD

**Issue by DSLituiev** [rstats-db/RSQLite#143] opened 2016-07-05 23:47 UTC
I am running the same dbSendQuery( "SELECT...") query on two systems (CentOS server and MacOSX local machine) on copies of the same file. On CentOS I am getting what I expect, and on Mac I get a shorter table of 500 rows and a warning:

Warning message: In sqliteSendQuery(conn, statement) : Closing result set with pending rows

Is there way to find out what is going on?

**Comment by krlmlr** [comment] 2016-07-06 05:00
How many rows are there? What does the query code look like? Can you replicate the problem with a new database and some random data?

**Comment by bradhannigandaley** [comment] 2016-08-20 17:32
I've encountered the same issue, and found that in my case it's remedied by explicitly passing the argument `n=-1` to `dbFetch`, even though this is supposed to be the default value for that parameter.

**Comment by krlmlr** [comment] 2016-08-20 20:42
@bradhannigandaley: Thanks. Would you mind sharing your code and perhaps some (possibly artificial) data?

**Comment by krlmlr** [comment] 2016-08-21 21:52
Are you using the CRAN version of RSQLite? Don't forget to close open result sets with dbClearResult(), even if you have fetched all rows.

**Comment by krlmlr** [comment] 2017-04-03 20:43
Closing, because no reproducible example has been provided. Please file a new issue if the problem reappears.

**Closed by krlmlr** 2017-04-03 20:43 UTC
Labels: ready
