### ISSUE TITLE
RSQLite 2.0 issues with sqldf

### ISSUE THREAD

**Issue by eamoakohene** [rstats-db/RSQLite#219] opened 2017-06-24 09:40 UTC
RSQLite 2.0 appears not be working with sqldf. The following example fails:
`
 abc <- datasets::mtcars ;
sqldf::sqldf( 'select mpg from abc')
`
It produces the error :
**Error in rsqlite_send_query(conn@ptr, statement) : no such table: abc**

RSQLite version 1.1-2 runs the code above with no issues.

**Comment by krlmlr** [comment] 2017-06-24 10:07
This looks like a duplicate of #216, can you please try the [GitHub version](https://github.com/ggrothendieck/sqldf) of sqldf?

**Closed by krlmlr** 2017-06-24 10:07 UTC
