### ISSUE TITLE
Table not found

### ISSUE THREAD

**Issue by jacob-bedard-o2e** [rstats-db/RSQLite#221] opened 2017-06-27 16:36 UTC
The new RSQLite seems to break sqldf, apparently. It says it can't find my tables. I looked this up and the sqldf package team has traced this issue back to the new RSQLite version.

**Comment by krlmlr** [comment] 2017-06-27 17:11
Duplicate of #216 and #219. Please use the GitHub version of sqldf until the update has been pushed to CRAN.

**Closed by krlmlr** 2017-06-27 17:11 UTC

**Comment by krlmlr** [comment] 2017-06-27 17:13
Related: https://github.com/ggrothendieck/sqldf/issues/15
